Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-20.04-server-amd64"
  config.vm.box_version = "20210401.01"

  # Give a custom name for a VM created by this script for a Vagrant CLI
  config.vm.define "binance-pnd-build"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 2048
  end

  # cloud-init script
  config.vm.cloud_init :user_data do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = "/tmp/pnd-server/cloud-init-ci.yml"
  end

  # Currently "ubuntu/bionic64" on VirtualBox requires `type: "virtualbox"`
  # to make synced folder works.
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Add `vagrant` to Administrator
  config.vm.provision :shell, inline: "sudo usermod -a -G sudo vagrant"

end